version: "3.6"
services:
  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr
    ports:
      - 6767:6767
    restart: unless-stopped
    volumes:
      - ./bazarr/config:/config
      - ./data/movies:/movies
      - ./data/tv:/tv
  jackett:
    container_name: jackett
    image: cr.hotio.dev/hotio/jackett
    ports:
      - 9117:9117
    restart: unless-stopped
    volumes:
      - ./jackett/config:/config
      - ./data/downloads:/downloads
  plex:
    container_name: plex
    image: cr.hotio.dev/hotio/plex
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    restart: unless-stopped
    volumes:
      - ./plex/config:/config
      - ./plex/transcode:/transcode
      - ./data:/data
  qbittorrent:
    container_name: qbittorrent
    image: cr.hotio.dev/hotio/qbittorrent
    ports:
      - 8080:8080
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    volumes:
      - ./qbittorent/config:/config
      - ./data/downloads:/downloads
  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr
    ports:
      - 7878:7878
    restart: unless-stopped
    volumes:
      - ./radarr/config:/config
      - ./data/downloads:/downloads
      - ./data/movies:/movies
  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr
    ports:
      - 8989:8989
    restart: unless-stopped
    volumes:
      - ./sonarr/config:/config
      - ./data/downloads:/downloads
      - ./data/tv:/tv
