version: "3.6"
services:
  bazarr:
    container_name: bazarr
    env_file:
      - .env
    image: lscr.io/linuxserver/bazarr
    ports:
      - 6767:6767
    restart: unless-stopped
    volumes:
      - ./bazarr:/config
      - ./data/movies:/movies
      - ./data/tv:/tv
  jackett:
    container_name: jackett
    env_file:
      - .env
    image: lscr.io/linuxserver/jackett
    ports:
      - 9117:9117
    restart: unless-stopped
    volumes:
      - ./jackett/config:/config
      - ./jackett/blackhole:/blackhole
  plex:
    container_name: plex
    env_file:
      - .env
    image: lscr.io/linuxserver/plex
    ports:
      # access to the Plex Media Server
      - 32400:32400
      # access to the Plex DLNA Server
      # - 1900:1900
      # older Bonjour/Avahi network discovery
      # - 5353:5353/udp
      # controlling Plex for Roku via Plex Companion
      # - 8324:8324
      # current GDM network discovery
      # - 32410:32410/udp
      # - 32412:32412/udp
      # - 32413:32413/udp
      # - 32414:32414/udp
      # access to the Plex DLNA Server
      # - 32469:32469
    restart: unless-stopped
    volumes:
      - ./plex/config:/config
      - ./plex/transcode:/transcode
      - ./data/movies:/movies
      - ./data/tv:/tv
  qbittorrent:
    container_name: qbittorrent
    env_file:
      - .env
    image: lscr.io/linuxserver/qbittorrent
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./qbittorrent:/config
      - ./data/downloads:/downloads
  radarr:
    container_name: radarr
    env_file:
      - .env
    image: lscr.io/linuxserver/radarr
    ports:
      - 7878:7878
    restart: unless-stopped
    volumes:
      - ./radarr:/config
      - ./data/downloads:/downloads
      - ./data/movies:/movies
  sonarr:
    container_name: sonarr
    env_file:
      - .env
    image: lscr.io/linuxserver/sonarr
    ports:
      - 8989:8989
    restart: unless-stopped
    volumes:
      - ./sonarr:/config
      - ./data/downloads:/downloads
      - ./data/tv:/tv
